### PR TITLE
Clickable directory

### PR DESCRIPTION
**Pull request by adnan29979**
i tried a lot to reduce the space between directories. i couldn't. 
but regardless of that, its a working clickable directory system.

### CODE REVIEW

**Comment by si458** [comment]
image
oh very nice indeed and works too!
clickable directorys at the top so you dont have to keep going back then back then back etc!

**Comment by adnan29979** [comment]
i found a bug. 
once I click the download button by selecting a folder, then the directory displays multiple same folders in the same directory and then nothing really works. the clickable directory, the up button, root button, etc. nothing. nor the download of the folder starts. can you confirm if this actually happens @si458?

**Comment by si458** [comment]
I don't believe you can download a folder, but i could be mistaken

**Comment by adnan29979** [comment]
previously i personally could. 
If we don't have the properly functionality to download a folder, then I think i should add some exceptions to take care of the bug i just mentioned. 
btw, were u able to replicate the bug?

**Pull request merged**
