### PR TITLE
add clickable column header to sort files

### PR DESCRIPTION
**Pull request by adnan29979**
added clickable column header to sort files by name, size, date modified.

### CODE REVIEW

**Comment by si458** [comment]
this looks great! will look 2moz to confirm.

one thing tho is you have changed the date from dd-mm-yyyy to mm/dd/yyyy

that wont wash for me in UK here!?

could you maybe see if you can get the date format of your computer and use that to format?
or maybe add an option under settings to pick a file/folder date format? let end user pick?

**Comment by adnan29979** [comment]
yea okay sure. 
i changed it from dd-mm-yyyy to mm/dd/yyyy because when i clicked to sort in 'dd-mm-yyyy' format, it gave an error saying that this format cannot be converted to datetime or something like that. for that reason, i converted to the mm/dd/yyyy format so that the rest of the code 'understands' it.

**Comment by adnan29979** [comment]
nevertheless, im looking into it. no worries. 
(might take me some time. I'm travelling rn)

**Comment by si458** [comment]
> nevertheless, im looking into it. no worries. (might take me some time. I'm travelling rn)

no worries no rush!
i was literally only thinking the other day, why didnt the dam headers sort the files, turns out no code for it haha

**Comment by adnan29979** [comment]
please do check now, @si458. 
I changed my windows machine's date/time format and they work fine in my case. 
Im not sure about linux or mac tho. can you check them if possible? i don't have the resources to check them unfortunately.

**Comment by si458** [comment]
can confirm all seems to work here!
USA:
image
UK:
image
Mac (using wine stable 9.0):
image

**Comment by adnan29979** [comment]
Perfff!!

**Pull request merged**
