### PR TITLE
Add RDP to doubleclick action combobox

### LINKED ISSUE #27: Doubleclick action combobox is missing RDP item
I noticed when setting the doubleclick action to SSH, it opened RDP.

When I look in below file, I see the items added to the doubleclick combobox in the device settings:
https://github.com/Ylianst/MeshCentralRouter/blob/b17045a4577c2cff6136f41d2f81379751077828/DeviceSettingsForm.resx#L174

Item 6 should be RDP and SSH and SCP should be item 7 and 8 according to setDoubleClickDeviceAction on mainform.
https://github.com/Ylianst/MeshCentralRouter/blob/b17045a4577c2cff6136f41d2f81379751077828/MainForm.cs#L287

### PR DESCRIPTION
**Pull request by omiT-84**
The doubleclick combobox was missing the RDP entry.
Might be better to fill this list dynamically, so the Index will always correspond with the correct item, but at least it's working now.
Fixes #27

### CODE REVIEW

**Comment by omiT-84** [comment]
@si458 
Simon, you are the man. Thank you for your time and effort you put into this stuff.
Also big thanks to all the other guys supporting this project of course.

**Comment by si458** [comment]
Latest version if you wanted to test, including all the latest PRs!
if it asks about downloading a never version, say NO, otherwise it downloads the version from your meshcentral server
[MeshCentralRouter.zip](https://github.com/user-attachments/files/16015683/MeshCentralRouter.zip)

**Comment by omiT-84** [comment]
So... I said tomorrow did'nt I?
I totally forgot to send feedback.
Better late then never, but I tested it and it is working as expected.

**Comment by si458** [comment]
@omiT-84 glad its working!

**Pull request merged**
